#################### default parameters ############################
# favicon module: https://github.com/gethugothemes/hugo-modules/tree/master/images#favicon-implementation
favicon = "images/favicon.svg"
# logo module: https://github.com/gethugothemes/hugo-modules/tree/master/images#logo-implementation
logo = ""
logo_darkmode = ""
logo_width = "160px"
logo_height = "32px"
logo_webp = true
logo_text = "CTO de Lyon"
navbar_fixed = true
theme_switcher = true
theme_default = "system"
mainSections = ["blog"]
contact_form_action = "#"
google_tag_manager = ""
google_adsense = ""
custom_script = ""
copyright = "© 2026 CTO De Lyon. Tous droits réservés."

[preloader]
enable = false
preloader = ""

[navigation_button]
enable = true
label = "Rejoignez nous"
link = "https://luma.com/cto-de-lyon?k=c"

[search]
enable = false
primary_color = "#121212"
include_sections = ["blog"]
show_image = true
show_description = true
show_tags = true
show_categories = true

[announcement]
enable = false
expire_days = 7
content = ""

[metadata]
keywords = ["CTO", "Lyon"]
description = "CTO de Lyon"
author = ""
twitter = ""
image = "images/og-image.png"

[site_verification]
google = ""
bing = ""
baidu = ""
facebook = ""
mastodon = ""

[cookies]
enable = false
expire_days = 60
content = "This site uses cookies."
button = "I Accept"

[mermaid]
js_url = 'https://cdn.jsdelivr.net/npm/mermaid@latest/dist/mermaid.esm.min.mjs'

[widgets]
sidebar = ["categories", "tags"]

[google_map]
enable = false
map_api_key = ""
map_latitude = ""
map_longitude = ""
map_marker = "images/marker.png"

[subscription]
enable = false
mailchimp_form_action = ""
mailchimp_form_name = ""

