baseURL = 'https://cto-de-lyon.fr/'
languageCode = 'fr-fr'
title = 'CTO de Lyon'
defaultContentLanguage = 'fr'
theme = 'hugoplate'
disableKinds = ['taxonomy', 'term']

[outputs]
home = ["HTML", "RSS"]

# Styles personnalis√©s (scroll smooth + bouton retour en haut)
[[params.plugins.css]]
link = "css/scroll.css"
lazy = false
